version: '3.2'

services:

  shop_frontend:
    container_name: shop_frontend
    working_dir: /app
    build: frontend
    ports:
      - 8080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  shop_backend:
    container_name: shop_backend
    working_dir: /app
    build: backend
    ports:
      - 8180:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  shop_db:
    container_name: shop_db
    image: mysql:5.7
    ports:
    - 3377:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret